logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming http requests
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE # Outgoing http requests
    org.springframework.jdbc.core: DEBUG # SQL

twitch:
  client-id: "h9baux6vwaxg20jtsyt036nae2e9id"
  secret: "ynzbvm54abelpq6cm9ja3dk1pb8am2"

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://twitch-instance.cj0u8gk2kmeb.us-east-1.rds.amazonaws.com:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:Richard429}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"